--------------------------------------------------------
--  Constraints for Table AUTHOR
--------------------------------------------------------

  ALTER TABLE "AUTHOR" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "AUTHOR" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "AUTHOR" ADD CONSTRAINT "AUTHOR_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "AUTHOR" ADD CONSTRAINT "AUTHOR_CHK_BIRTH_YEAR" CHECK (BIRTH_YEAR <> 0) ENABLE;
--------------------------------------------------------
--  Constraints for Table BOOK
--------------------------------------------------------

  ALTER TABLE "BOOK" MODIFY ("ISBN" NOT NULL ENABLE);
  ALTER TABLE "BOOK" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "BOOK" MODIFY ("BOOK_LANGUAGE" NOT NULL ENABLE);
  ALTER TABLE "BOOK" MODIFY ("PAGE_COUNT" NOT NULL ENABLE);
  ALTER TABLE "BOOK" ADD CONSTRAINT "BOOK_PK" PRIMARY KEY ("ISBN")
  USING INDEX  ENABLE;
  ALTER TABLE "BOOK" ADD CONSTRAINT "BOOK_CHK_PUBLICATION_YEAR" CHECK (PUBLICATION_YEAR <> 0) ENABLE;
  ALTER TABLE "BOOK" ADD CONSTRAINT "BOOK_CHK_PAGE_COUNT" CHECK (PAGE_COUNT > 0) ENABLE;
  ALTER TABLE "BOOK" ADD CONSTRAINT "BOOK_CHK_IS_ACTIVE" CHECK (IS_ACTIVE IN ('Y','N')) ENABLE;
  ALTER TABLE "BOOK" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "BOOK" MODIFY ("PUBLISHER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOOK_AUTHOR
--------------------------------------------------------

  ALTER TABLE "BOOK_AUTHOR" MODIFY ("ISBN" NOT NULL ENABLE);
  ALTER TABLE "BOOK_AUTHOR" MODIFY ("AUTHOR_ID" NOT NULL ENABLE);
  ALTER TABLE "BOOK_AUTHOR" ADD CONSTRAINT "BOOKAUTHOR_PK" PRIMARY KEY ("ISBN", "AUTHOR_ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table BOOK_CATEGORY
--------------------------------------------------------

  ALTER TABLE "BOOK_CATEGORY" MODIFY ("ISBN" NOT NULL ENABLE);
  ALTER TABLE "BOOK_CATEGORY" MODIFY ("CATEGORY_ID" NOT NULL ENABLE);
  ALTER TABLE "BOOK_CATEGORY" ADD CONSTRAINT "BOOKCATEGORY_PK" PRIMARY KEY ("ISBN", "CATEGORY_ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table BOOK_COPY
--------------------------------------------------------

  ALTER TABLE "BOOK_COPY" MODIFY ("BARCODE" NOT NULL ENABLE);
  ALTER TABLE "BOOK_COPY" MODIFY ("ISBN" NOT NULL ENABLE);
  ALTER TABLE "BOOK_COPY" MODIFY ("SHELF_ID" NOT NULL ENABLE);
  ALTER TABLE "BOOK_COPY" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "BOOK_COPY" MODIFY ("ACQUISITION_DATE" NOT NULL ENABLE);
  ALTER TABLE "BOOK_COPY" ADD CONSTRAINT "BOOK_COPY_PK" PRIMARY KEY ("BARCODE")
  USING INDEX  ENABLE;
  ALTER TABLE "BOOK_COPY" ADD CONSTRAINT "BOOK_COPY_CHK_STATUS" CHECK (status in ('Available', 'Loaned', 'Reserved', 'Lost', 'Unavailable')) ENABLE;
--------------------------------------------------------
--  Constraints for Table CATEGORY
--------------------------------------------------------

  ALTER TABLE "CATEGORY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CATEGORY" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "CATEGORY" ADD CONSTRAINT "CATEGORY_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "CATEGORY" ADD CONSTRAINT "CATEGORY_UK_NAME" UNIQUE ("NAME")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table LIBRARIAN
--------------------------------------------------------

  ALTER TABLE "LIBRARIAN" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "LIBRARIAN" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "LIBRARIAN" MODIFY ("PASSWORD_HASH" NOT NULL ENABLE);
  ALTER TABLE "LIBRARIAN" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "LIBRARIAN" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "LIBRARIAN" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "LIBRARIAN" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "LIBRARIAN" ADD CONSTRAINT "LIBRARIAN_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "LIBRARIAN" ADD CONSTRAINT "LIBRARIAN_UK_USERNAME" UNIQUE ("USERNAME")
  USING INDEX  ENABLE;
  ALTER TABLE "LIBRARIAN" ADD CONSTRAINT "LIBRARIAN_CHK_IS_ACTIVE" CHECK (IS_ACTIVE in ('Y','N')) ENABLE;
  ALTER TABLE "LIBRARIAN" ADD CONSTRAINT "LIBRARIAN_CHK_EMAIL" CHECK (REGEXP_LIKE(email, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')) ENABLE;
  ALTER TABLE "LIBRARIAN" ADD CONSTRAINT "LIBRARIAN_UK_EMAIL" UNIQUE ("EMAIL")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table LOAN
--------------------------------------------------------

  ALTER TABLE "LOAN" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "LOAN" MODIFY ("BARCODE" NOT NULL ENABLE);
  ALTER TABLE "LOAN" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "LOAN" MODIFY ("LIBRARIAN_ID" NOT NULL ENABLE);
  ALTER TABLE "LOAN" MODIFY ("LOAN_DATE" NOT NULL ENABLE);
  ALTER TABLE "LOAN" MODIFY ("DUE_DATE" NOT NULL ENABLE);
  ALTER TABLE "LOAN" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "LOAN" ADD CONSTRAINT "LOAN_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "LOAN" ADD CONSTRAINT "LOAN_CHK_STATUS" CHECK (STATUS in ('Active',  'Returned',  'Lost' , 'Cancelled')) ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "MEMBER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MEMBER" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "MEMBER" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "MEMBER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "MEMBER" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "MEMBER" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "MEMBER" MODIFY ("REGISTRATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "MEMBER" MODIFY ("DATE_OF_BIRTH" NOT NULL ENABLE);
  ALTER TABLE "MEMBER" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "MEMBER" ADD CONSTRAINT "MEMBER_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "MEMBER" ADD CONSTRAINT "MEMBER_CHK_EMAIL" CHECK (REGEXP_LIKE(email, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')) ENABLE;
  ALTER TABLE "MEMBER" ADD CONSTRAINT "MEMBER_CHK_STATUS" CHECK (STATUS IN ('Active', 'Inactive', 'Suspended')) ENABLE;
  ALTER TABLE "MEMBER" ADD CONSTRAINT "MEMBER_CHK_PHONE" CHECK (REGEXP_LIKE(phone, '^\+?[1-9][0-9]{6,14}$')) ENABLE;
  ALTER TABLE "MEMBER" ADD CONSTRAINT "MEMBER_CHK_SUSPENSION" CHECK ((STATUS = 'Suspended' AND SUSPENSION_END_DATE IS NOT NULL) OR (STATUS IN ('Active', 'Inactive') AND SUSPENSION_END_DATE IS NULL)) ENABLE;
--------------------------------------------------------
--  Constraints for Table PUBLISHER
--------------------------------------------------------

  ALTER TABLE "PUBLISHER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PUBLISHER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "PUBLISHER" ADD CONSTRAINT "PUBLISHER_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "PUBLISHER" ADD CONSTRAINT "PUBLISHER_UK_NAME" UNIQUE ("NAME")
  USING INDEX  ENABLE;
  ALTER TABLE "PUBLISHER" ADD CONSTRAINT "PUBLISHER_CHK_EMAIL" CHECK (REGEXP_LIKE(email, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')) ENABLE;
  ALTER TABLE "PUBLISHER" ADD CONSTRAINT "PUBLISHER_CHK_PHONE" CHECK (REGEXP_LIKE(phone, '^\+?[1-9][0-9]{6,14}$')) ENABLE;
--------------------------------------------------------
--  Constraints for Table RESERVATION
--------------------------------------------------------

  ALTER TABLE "RESERVATION" ADD CONSTRAINT "RESERVATION_CHK_STATUS" CHECK (STATUS in ( 'Active', 'Ready', 'Fulfilled', 'Cancelled', 'Expired')) ENABLE;
  ALTER TABLE "RESERVATION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "RESERVATION" MODIFY ("ISBN" NOT NULL ENABLE);
  ALTER TABLE "RESERVATION" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "RESERVATION" MODIFY ("RESERVATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "RESERVATION" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "RESERVATION" ADD CONSTRAINT "RESERVATION_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table SHELF
--------------------------------------------------------

  ALTER TABLE "SHELF" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SHELF" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "SHELF" MODIFY ("FLOOR" NOT NULL ENABLE);
  ALTER TABLE "SHELF" MODIFY ("SECTION" NOT NULL ENABLE);
  ALTER TABLE "SHELF" ADD CONSTRAINT "SHELF_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SHELF" ADD CONSTRAINT "SHELF_UK_CODE" UNIQUE ("CODE")
  USING INDEX  ENABLE;
